controller:
  replicaCount: 2
  ingressClass: private-nginx
  nodeSelector:
    beta.kubernetes.io/os: linux
  publishService:
    enabled: true
  service:
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-internal: true
    externalTrafficPolicy: Local
  config:
    log-format-escape-json: 'true'
    log-format-upstream: '{"time_date": "$time_iso8601",
                           "client": "$remote_addr",
                           "host": "$http_host",
                           "scheme": "$scheme",
                           "request_method": "$request_method",
                           "request_uri": "$uri",
                           "request_id": "$request_id",
                           "status": $status,
                           "upstream_addr": "$upstream_addr",
                           "upstream_status": $upstream_status,
                           "request_time": $request_time,
                           "upstream_response_time": $upstream_response_time,
                           "upstream_connect_time": $upstream_connect_time,
                           "upstream_header_time": $upstream_header_time}'
defaultBackend:
  nodeSelector:
    beta.kubernetes.io/os: linux
